apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: counter-backend
  labels:
    project: counter
spec:
  podSelector:
    matchLabels:
      app: counter-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: counter-frontend
      ports:
        - protocol: TCP
          port: 8000
