apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
  labels:
    project: counter
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.backendReplicas }}
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
        project: counter
    spec:
      serviceAccountName: migration-job-read
      initContainers:
        - name: wait-for-migrations
          image: sikalabs/kubectl
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 2 && kubectl wait --for=condition=complete --timeout=600s job/backend-migration-{{ .Release.Revision }}"
      containers:
        - name: main
          image: {{ .Values.backendImage }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS
              value: redis
            - name: SLOW_START
              value: {{ .Values.backend_SLOW_START | quote }}
            - name: EXTRA_TEXT
              value: {{ .Values.backend_EXTRA_TEXT | quote }}
          startupProbe:
            periodSeconds: 1
            failureThreshold: 60
            httpGet:
              path: /readyz
              port: 8000
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /livez
              port: 8000
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi

