apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend
  labels:
    project: counter
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.frontendReplicas }}
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
        project: counter
    spec:
      volumes:
        - name: health
          emptyDir: {}
      initContainers:
        - name: wait-for-backend
          image: busybox
          command:
            - sh
            - -c
            - until wget -q --spider http://counter-backend/api/status; do echo 'Waiting for backend...'; sleep 2; done; echo 'Backend is up!'
        - name: wait-for-backend-slu
          image: ghcr.io/sikalabs/slu:v0.92.0
          command:
            - sh
            - -c
            - slu wait-for tcp -a counter-backend:80
        - name: set-healthy
          image: busybox
          command:
            - touch
            - /tmp/health/healthy
          volumeMounts:
            - name: health
              mountPath: /tmp/health
      containers:
        - name: main
          image: {{ .Values.frontendImage }}
          ports:
            - containerPort: 3000
          env:
            - name: API_ORIGIN
              value: http://counter-backend
            - name: FONT_COLOR
              value: {{ .Values.frontend_FONT_COLOR | quote }}
            - name: BACKGROUND_COLOR
              value: {{ .Values.frontend_BACKGROUND_COLOR | quote }}
            - name: FAIL_ON_ERROR
              value: {{ .Values.frontend_FAIL_ON_ERROR | quote }}
          startupProbe:
            periodSeconds: 1
            failureThreshold: 60
            httpGet:
              path: /api/livez
              port: 3000
          livenessProbe:
            failureThreshold: 1
            exec:
              command:
                - cat
                - /tmp/health/healthy
          volumeMounts:
            - name: health
              mountPath: /tmp/health
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi

