apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-backup
data:
  tergum.yaml: |
    Meta:
      SchemaVersion: 3
    Telemetry:
      CollectBackupLog: true
      CollectHostData: true
    Backups:
      - ID: redis
        Source:
          Redis:
            Host: redis
            Port: 6379
        Targets:
          - ID: file
            File:
              Dir: /backups
              Prefix: redis
              Suffix: rdb
          - ID: azure-blob
            AzureBlob:
              AccountName: example7807093848
              AccountKey: $TERGUM_AZURE_BLOB_ACCOUNT_KEY
              ContainerName: example
              Prefix: redis
              Suffix: rdb
