apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
spec:
  # https://crontab.guru/
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: redis-backup
            - name: backups
              persistentVolumeClaim:
                claimName: redis-backup
          containers:
            - name: main
              image: ghcr.io/tergum-extra/redis-with-tergum:8-tergum-v0.42.0
              args:
                - /bin/sh
                - -c
                - tergum backup -c /config/tergum.yaml --expand-env
              envFrom:
                - secretRef:
                    name: redis-backup
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: backups
                  mountPath: /backups
